### ISSUE TITLE
KeyError 'items'

### ISSUE THREAD

**Issue by fullonic** [PacktPublishing/Modern-Python-Standard-Library-Cookbook#1]
Hi, 
when running the example code ex 7, the Bunch class, I'm getting a key error when trying to get the items.

https://github.com/PacktPublishing/Modern-Python-Standard-Library-Cookbook/blob/4f53e3ab7b61aca1cca9343e7421e170280cd5b5/Chapter01/datastructures_07.py#L1

doing `b.items()`
results in:
````
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-c4712c4109ea> in __getattribute__(self, key)
     11         try:
---> 12             return self[key]
     13         except KeyError:

KeyError: 'items'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
<ipython-input-29-ead5e7ea8f9b> in <module>
----> 1 print(b.items())

<ipython-input-13-c4712c4109ea> in __getattribute__(self, key)
     12             return self[key]
     13         except KeyError:
---> 14             raise AttributeError(key)
     15 
     16     def __setattr__(self, key, value):

AttributeError: items
````
I'm using Python 3.7.3
Thanks

**Comment by amol-** [comment]
Hi, thanks for the report.

You are correct that `Bunch.items` is unavailable as a function. That was on purpose as the Bunch is meant to behave like an object and expose only attributes that were set on the object at creation time. That prevented dict attributes from conflicting with your own object attributes.

The **How it works** section in the attempt of pointing out that in the end everything is stored in a dictionary does `b.items()` to show the content of the dictionary. 
That is confusing as it suggests it's something you can do, but it was in fact meant to do `dict.items(b)` as no `items` attribute was assigned to the `Bunch` in the snippet.

```
>>> b = Bunch(a=5)
>>> b.items()
AttributeError: items
>>> dict.items(b)
[('a', 5)]
```

If you want to actually be able to use the `dict` methods you can use the alternative `Bunch` implementation that is proposed in the **There is More** section. That one acts less as a real object and more as a dict preserving all properties of a dict (which can cause problems if the object you are trying to represent with the Bunch was meant to have a conflicting attribute)

```
>>> class Bunch(dict):
...     def __init__(self, **kwds):
...         super(Bunch, self).__init__(**kwds)
...         self.__dict__ = self
>>> b = Bunch(a=5)
>>> b.items()
[('a', 5)]
```

an errata corrige was already suggested in the past for the **How it works** section and I hope it will be published as soon as possible thus solving the confusion.
